### ISSUE TITLE
Support of multiple windows

### ISSUE THREAD

**Issue by dvzubarev** [enoson/eno.el#3]
Hello,
It is not a bug, but the feature request.
It would be nice for eno to work across multiple opened windows (e.g. copy a symbol from an active window to an inactive one without switching to the inactive window).

**Comment by enoson** [comment]
Good idea, but it's not supported by design, cause it may generate too much hints.
If you want to do it yourself, check the function "eno", you need to get the "ovs" of multiple windows to pass to "eno-ov-select".
