### ISSUE TITLE
eno--add-all-two-letter-hints: Symbol's function definition is void: --find

### ISSUE THREAD

**Issue by novoid** [enoson/eno.el#4]
Hi!

GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.5) of 2015-03-07 on trouble, modified by Debian

eno-20151229.212 via package-install

When I invoke, e.g., `eno-word-goto`, I get the error message:

```
eno--add-all-two-letter-hints: Symbol's function definition is void: --find
```

I can see that my version doesn't differ from https://github.com/enoson/eno.el/blob/master/eno.el with that respect.

I also added your dependencies explicitely via `use-package dash...` and `use-package edit-at-point...` before the `use-package eno...` which did not change the situation.

Where is your `--find` function defined?

**Comment by enoson** [comment]
--find is a function of dash.el, so it might be dash is not loading.
I've updated the dash version, if still not working, you can try copy&paste the entire dash.el to eno.el..

**Comment by novoid** [comment]
Oh, I think I found the source of my issue: dash version 20131223.933 seems rather old.

I removed the elpa folder of the old version and installed a newer version (dash-20151216.1315) manually. This version contains `(defalias '--find '--first)`. However, I now get:

```
eno--add-all-two-letter-hints: Invalid function: --find
```

Then I replaces `--find` with `--first` in eno.el. No change.

After that, I copied the whole dash.el to the beginning of eno.el. No change.

Hm, no idea left for now. Do you have any suggestion?

**Comment by enoson** [comment]
How about delete the elpa folder and reinstall all the packages with the latest version?

**Comment by novoid** [comment]
Deleting all local elpa folders?

Besides: since I am using use-package from https://github.com/jwiegley/use-package I did not specify to get the older version installed. So I think that re-installing all packages might not necessarily end up with most recent packages.

**Comment by enoson** [comment]
It's not necessary, you just need to ensure dash is properly installed.

**Comment by enoson** [comment]
Not sure about your problem, this is the most straightforward way I know.

**Comment by enoson** [comment]
Since it's not a issue of eno.el, I'll close for now.
